name: CI CD Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Run tests and capture results
        run: |
          mkdir -p artifacts
          # Capture all output (stdout+stderr) to a file while still printing in CI
          npm test 2>&1 | tee artifacts/test-results.txt
        continue-on-error: false

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: artifacts/test-results.txt
          if-no-files-found: error
          retention-days: 7

  deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build project (if needed)
        run: npm run build || echo "No build script"

      - name: Restart Node app with PM2
        run: |
          pm2 delete node-app || true
          pm2 start npm --name "node-app" -- start
          pm2 save
          pm2 status

      - name: Restart Nginx
        run: |
          echo "Restarting Nginx..."
          sudo systemctl reload nginx || sudo systemctl restart nginx
          sudo systemctl status nginx --no-pager


